//go:build !js

// Package prism.v1 defines the Twirp service surface for Prism.
//
// All spec-carrying requests pass the spec as a JSON-encoded string
// rather than re-modeling the Spec inside protobuf. There is one
// source of truth for the Spec — the Go types under `spec/` and the
// JSON Schema bundle under `schema/v1/`. Re-modeling here would
// guarantee drift.
//
// Scene IR and LogicalPlan are returned as JSON strings for the same
// reason.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          string                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Theme         string                 `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotRequest) Reset() {
	*x = PlotRequest{}
	mi := &file_rpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotRequest) ProtoMessage() {}

func (x *PlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotRequest.ProtoReflect.Descriptor instead.
func (*PlotRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *PlotRequest) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *PlotRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PlotRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *PlotRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PlotRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type PlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotResponse) Reset() {
	*x = PlotResponse{}
	mi := &file_rpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotResponse) ProtoMessage() {}

func (x *PlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotResponse.ProtoReflect.Descriptor instead.
func (*PlotResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *PlotResponse) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *PlotResponse) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *PlotResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          string                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_rpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequest) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Errors        []*ValidateError       `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_rpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateResponse) GetErrors() []*ValidateError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fixups        []string               `protobuf:"bytes,3,rep,name=fixups,proto3" json:"fixups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateError) Reset() {
	*x = ValidateError{}
	mi := &file_rpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateError) ProtoMessage() {}

func (x *ValidateError) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateError.ProtoReflect.Descriptor instead.
func (*ValidateError) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidateError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateError) GetFixups() []string {
	if x != nil {
		return x.Fixups
	}
	return nil
}

type SceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          string                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Theme         string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneRequest) Reset() {
	*x = SceneRequest{}
	mi := &file_rpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneRequest) ProtoMessage() {}

func (x *SceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneRequest.ProtoReflect.Descriptor instead.
func (*SceneRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *SceneRequest) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *SceneRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *SceneRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SceneRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneJson     string                 `protobuf:"bytes,1,opt,name=scene_json,json=sceneJson,proto3" json:"scene_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneResponse) Reset() {
	*x = SceneResponse{}
	mi := &file_rpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneResponse) ProtoMessage() {}

func (x *SceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneResponse.ProtoReflect.Descriptor instead.
func (*SceneResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *SceneResponse) GetSceneJson() string {
	if x != nil {
		return x.SceneJson
	}
	return ""
}

type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          string                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_rpc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *PlanRequest) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanJson      string                 `protobuf:"bytes,1,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_rpc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *PlanResponse) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

type DatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetsRequest) Reset() {
	*x = DatasetsRequest{}
	mi := &file_rpc_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetsRequest) ProtoMessage() {}

func (x *DatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetsRequest.ProtoReflect.Descriptor instead.
func (*DatasetsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{9}
}

type DatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*Dataset             `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetsResponse) Reset() {
	*x = DatasetsResponse{}
	mi := &file_rpc_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetsResponse) ProtoMessage() {}

func (x *DatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetsResponse.ProtoReflect.Descriptor instead.
func (*DatasetsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{10}
}

func (x *DatasetsResponse) GetDatasets() []*Dataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type Dataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_rpc_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_rpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *Dataset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dataset) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_rpc_service_proto protoreflect.FileDescriptor

const file_rpc_service_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/service.proto\x12\bprism.v1\"}\n" +
	"\vPlotRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\tR\x04spec\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05theme\x18\x03 \x01(\tR\x05theme\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\"T\n" +
	"\fPlotResponse\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"%\n" +
	"\x0fValidateRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\tR\x04spec\"S\n" +
	"\x10ValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12/\n" +
	"\x06errors\x18\x02 \x03(\v2\x17.prism.v1.ValidateErrorR\x06errors\"U\n" +
	"\rValidateError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06fixups\x18\x03 \x03(\tR\x06fixups\"f\n" +
	"\fSceneRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\tR\x04spec\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\".\n" +
	"\rSceneResponse\x12\x1d\n" +
	"\n" +
	"scene_json\x18\x01 \x01(\tR\tsceneJson\"!\n" +
	"\vPlanRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\tR\x04spec\"+\n" +
	"\fPlanResponse\x12\x1b\n" +
	"\tplan_json\x18\x01 \x01(\tR\bplanJson\"\x11\n" +
	"\x0fDatasetsRequest\"A\n" +
	"\x10DatasetsResponse\x12-\n" +
	"\bdatasets\x18\x01 \x03(\v2\x11.prism.v1.DatasetR\bdatasets\"5\n" +
	"\aDataset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source2\xb9\x02\n" +
	"\x05Prism\x125\n" +
	"\x04Plot\x12\x15.prism.v1.PlotRequest\x1a\x16.prism.v1.PlotResponse\x12A\n" +
	"\bValidate\x12\x19.prism.v1.ValidateRequest\x1a\x1a.prism.v1.ValidateResponse\x128\n" +
	"\x05Scene\x12\x16.prism.v1.SceneRequest\x1a\x17.prism.v1.SceneResponse\x125\n" +
	"\x04Plan\x12\x15.prism.v1.PlanRequest\x1a\x16.prism.v1.PlanResponse\x12E\n" +
	"\fListDatasets\x12\x19.prism.v1.DatasetsRequest\x1a\x1a.prism.v1.DatasetsResponseB&Z$github.com/frankbardon/prism/rpc;rpcb\x06proto3"

var (
	file_rpc_service_proto_rawDescOnce sync.Once
	file_rpc_service_proto_rawDescData []byte
)

func file_rpc_service_proto_rawDescGZIP() []byte {
	file_rpc_service_proto_rawDescOnce.Do(func() {
		file_rpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_service_proto_rawDesc), len(file_rpc_service_proto_rawDesc)))
	})
	return file_rpc_service_proto_rawDescData
}

var file_rpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rpc_service_proto_goTypes = []any{
	(*PlotRequest)(nil),      // 0: prism.v1.PlotRequest
	(*PlotResponse)(nil),     // 1: prism.v1.PlotResponse
	(*ValidateRequest)(nil),  // 2: prism.v1.ValidateRequest
	(*ValidateResponse)(nil), // 3: prism.v1.ValidateResponse
	(*ValidateError)(nil),    // 4: prism.v1.ValidateError
	(*SceneRequest)(nil),     // 5: prism.v1.SceneRequest
	(*SceneResponse)(nil),    // 6: prism.v1.SceneResponse
	(*PlanRequest)(nil),      // 7: prism.v1.PlanRequest
	(*PlanResponse)(nil),     // 8: prism.v1.PlanResponse
	(*DatasetsRequest)(nil),  // 9: prism.v1.DatasetsRequest
	(*DatasetsResponse)(nil), // 10: prism.v1.DatasetsResponse
	(*Dataset)(nil),          // 11: prism.v1.Dataset
}
var file_rpc_service_proto_depIdxs = []int32{
	4,  // 0: prism.v1.ValidateResponse.errors:type_name -> prism.v1.ValidateError
	11, // 1: prism.v1.DatasetsResponse.datasets:type_name -> prism.v1.Dataset
	0,  // 2: prism.v1.Prism.Plot:input_type -> prism.v1.PlotRequest
	2,  // 3: prism.v1.Prism.Validate:input_type -> prism.v1.ValidateRequest
	5,  // 4: prism.v1.Prism.Scene:input_type -> prism.v1.SceneRequest
	7,  // 5: prism.v1.Prism.Plan:input_type -> prism.v1.PlanRequest
	9,  // 6: prism.v1.Prism.ListDatasets:input_type -> prism.v1.DatasetsRequest
	1,  // 7: prism.v1.Prism.Plot:output_type -> prism.v1.PlotResponse
	3,  // 8: prism.v1.Prism.Validate:output_type -> prism.v1.ValidateResponse
	6,  // 9: prism.v1.Prism.Scene:output_type -> prism.v1.SceneResponse
	8,  // 10: prism.v1.Prism.Plan:output_type -> prism.v1.PlanResponse
	10, // 11: prism.v1.Prism.ListDatasets:output_type -> prism.v1.DatasetsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_service_proto_init() }
func file_rpc_service_proto_init() {
	if File_rpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_proto_rawDesc), len(file_rpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_proto_goTypes,
		DependencyIndexes: file_rpc_service_proto_depIdxs,
		MessageInfos:      file_rpc_service_proto_msgTypes,
	}.Build()
	File_rpc_service_proto = out.File
	file_rpc_service_proto_goTypes = nil
	file_rpc_service_proto_depIdxs = nil
}
