//go:build !js && !wasm

package geodata

import (
	"fmt"
	"path/filepath"
	"sync"

	"github.com/spf13/afero"
)

// Host-side tier geometry is loaded from a runtime directory rather
// than embedded into the binary. The tier files (world-110m.geo.json,
// world-50m.geo.json, admin1-50m.geo.json) remain committed to the
// repo as the source of truth (regenerated by `make geodata`), but the
// host binary no longer carries the ~2.7 MB of geometry bytes.
//
// Configure the load directory via SetHostBundleDir before the first
// geoshape encode. This is the host-side mirror of the WASM
// SetBundleURL/FetchTierBytes path in geometry_wasm.go.
//
// WASM builds fetch tiers over the network — see geometry_wasm.go.
var (
	hostBundleMu  sync.RWMutex
	hostBundleDir string
	// hostBundleFs is the filesystem tier files are read from. It
	// defaults to the OS filesystem; tests swap in an in-memory afero.Fs
	// (the package-internal seam keeps the public API minimal while still
	// honouring the hermetic-test rule).
	hostBundleFs afero.Fs = afero.NewOsFs()
)

// SetHostBundleDir configures the directory the host build reads tier
// geometry from. Each tier resolves to "<dir>/<tier>.geo.json". This is
// the host-side analogue of the WASM SetBundleURL. Safe for concurrent
// use; the directory is consulted lazily on first Lookup, so callers may
// set it any time before a geoshape mark is encoded.
func SetHostBundleDir(path string) {
	hostBundleMu.Lock()
	defer hostBundleMu.Unlock()
	hostBundleDir = path
}

// HostBundleDir returns the directory currently configured for tier
// geometry, or "" when none has been set. Symmetric with the WASM
// BundleURL accessor.
func HostBundleDir() string {
	hostBundleMu.RLock()
	defer hostBundleMu.RUnlock()
	return hostBundleDir
}

func isKnownTier(tier Tier) bool {
	for _, t := range AllTiers() {
		if t == tier {
			return true
		}
	}
	return false
}

// platformTierLoader reads raw tier-bundle bytes from the configured
// host directory. The returned errors distinguish the unset-directory
// case from the missing-tier-file case so a later layer can map them to
// distinct PRISM_* codes.
func platformTierLoader(tier Tier) ([]byte, error) {
	if !isKnownTier(tier) {
		return nil, fmt.Errorf("geodata: unknown tier %q", tier)
	}

	hostBundleMu.RLock()
	dir := hostBundleDir
	fs := hostBundleFs
	hostBundleMu.RUnlock()

	if dir == "" {
		return nil, ErrBundleDirUnset
	}

	path := filepath.Join(dir, string(tier)+".geo.json")
	raw, err := afero.ReadFile(fs, path)
	if err != nil {
		return nil, &TierMissingError{Tier: tier, Path: path, Err: err}
	}
	return raw, nil
}

// EmbeddedTierBytes returns the raw bundle bytes for the given tier as
// read from the configured host bundle directory. Host-only (the wasm
// build fetches over the network). Returns an error for unknown tiers,
// when no directory has been configured, or when the tier file is
// missing.
//
// The sole consumer (cmd/prism static-bundle) reads tier bytes through
// this seam to copy the geodata artifacts to disk.
func EmbeddedTierBytes(tier Tier) ([]byte, error) {
	return platformTierLoader(tier)
}

// EmbeddedManifestBytes returns the manifest.json bytes as embedded
// at build time. Available on both host and WASM builds because
// manifest.go has no platform constraint. The manifest stays embedded
// (it is small and needed by validate / inspect / plan without any
// runtime directory).
func EmbeddedManifestBytes() []byte {
	return manifestBytes
}
